const TILEINNERWIDTH = 210,
    TILEPADDING = 16,
    TILEWIDTH = TILEINNERWIDTH + 2 * TILEPADDING,
    SIDEBAR_WIDTH = 282;

export {
    TILEINNERWIDTH,
    TILEPADDING,
    TILEWIDTH,
    SIDEBAR_WIDTH
};

